name: primeobjective
favicon: null
layout_spectrum: 0.75542
typography_spectrum: 0.66047
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b1b2b7'
    - '#657584'
    - '#131321'
    - '#433e44'
    - '#efd6b6'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
